# Generated by Django 5.2.8 on 2025-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether verification email was successfully sent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp for verification code (5 minutes from generation)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address for authentication", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, help_text="6-digit verification code sent to user's email", max_length=6, null=True),
        ),
    ]
