# Generated by Django 5.2.8 on 2025-12-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_sent_alter_user_code_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_sent',
        ),
    ]
