# Generated by Django 4.2.16 on 2026-02-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_multi_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether organization subscription is active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('not_subscribed', 'Not Subscribed'), ('basic', 'Basic'), ('professional', 'Professional')], default='not_subscribed', help_text='Current subscription tier', max_length=20),
        ),
    ]
