# Generated by Django 4.2.16 on 2026-02-27 18:00

from django.db import migrations, models


def migrate_subscription_tiers(apps, schema_editor):
    """
    Data migration to:
    1. Convert 'free' tier to 'not_subscribed'
    2. Delete 'Default Organization'
    3. Update max_users based on subscription tier
    """
    Organization = apps.get_model('authentication', 'Organization')
    
    # Delete Default Organization
    Organization.objects.filter(name='Default Organization').delete()
    
    # Update subscription tiers and max_users
    for org in Organization.objects.all():
        # Convert old 'free' tier to 'not_subscribed'
        if org.subscription_tier == 'free':
            org.subscription_tier = 'not_subscribed'
            org.max_users = 1
        # Update max_users based on tier
        elif org.subscription_tier == 'basic':
            org.max_users = 5
        elif org.subscription_tier == 'professional':
            org.max_users = 20
        
        org.save()


def reverse_migration(apps, schema_editor):
    """Reverse data migration (convert back to old tier names)"""
    Organization = apps.get_model('authentication', 'Organization')
    
    for org in Organization.objects.all():
        if org.subscription_tier == 'not_subscribed':
            org.subscription_tier = 'free'
            org.max_users = 5
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether organization subscription is active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=1, help_text='Maximum number of users allowed in this organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('not_subscribed', 'Not Subscribed'), ('basic', 'Basic plan'), ('professional', 'Professional plan')], default='not_subscribed', help_text='Current subscription tier', max_length=20),
        ),
        # Run data migration to update existing data
        migrations.RunPython(migrate_subscription_tiers, reverse_migration),
    ]
