# Generated by Django 4.2.16 on 2026-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether organization subscription is active'),
        ),
    ]
