# Generated by Django 4.2.16 on 2026-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_convert_paths_to_relative'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_timesta_0459bf_idx',
            old_name='alerts_aler_timesta_12837f_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_threat__77c12f_idx',
            old_name='alerts_aler_threat__097f80_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='ml_classification',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='ml_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='ml_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='ml_threat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threat_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['ml_processed', '-timestamp'], name='alerts_aler_ml_proc_69e48b_idx'),
        ),
    ]
