"""
Django settings for ThreatEye project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# ===== PROJECT PATHS =====
BASE_DIR = Path(__file__).resolve().parent.parent


# ===== CORE DJANGO SETTINGS =====
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lqgk5gj7f)o&pz_98dg@e!0r#=zhi=2i2h9rut$6r49cvr^4=p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# List of hosts allowed to serve this Django site (empty = localhost only during development)
ALLOWED_HOSTS = []


# ===== INSTALLED APPLICATIONS =====
# Core Django: admin, auth, sessions, static files
# Third-party: REST, CORS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'authentication',
    'subscription',
    'alerts',
]

# ===== MIDDLEWARE STACK =====
# Security, sessions, CORS, auth, messages, clickjacking protection
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Main URL configuration - maps URLs to views
ROOT_URLCONF = 'ThreatEye.urls'

# ===== TEMPLATE ENGINE =====
# Django template rendering configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application for production deployment
WSGI_APPLICATION = 'ThreatEye.wsgi.application'


# ===== DATABASE CONFIGURATION =====
# MySQL connection for alerts, users, subscriptions

import pymysql
pymysql.version_info = (2, 2, 8, "final", 0)
pymysql.install_as_MySQLdb()

# Bypass MariaDB version check for Django 4.2+ (requires 10.6, found 10.4)
from django.db.backends.base.base import BaseDatabaseWrapper
BaseDatabaseWrapper.check_database_version_supported = lambda self: None

# Disable RETURNING clause for MariaDB < 10.5
from django.db.backends.mysql.features import DatabaseFeatures
DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)
DatabaseFeatures.can_return_rows_from_bulk_insert = property(lambda self: False)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'threateye',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# ===== PASSWORD VALIDATION =====
# Strong passwords: not similar to user data, min length, not common, not all numeric
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===== INTERNATIONALIZATION & LOCALIZATION =====
# Set default language and timezone
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ===== STATIC FILES (CSS, JAVASCRIPT, IMAGES) =====
# Static file serving URL
STATIC_URL = 'static/'

# Default primary key field type - use 64-bit integers for large datasets
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== CUSTOM AUTHENTICATION =====
# Custom User model with email-based auth (not username)
AUTH_USER_MODEL = 'authentication.User'

# ===== REST FRAMEWORK API CONFIGURATION =====
# JWT authentication for all API endpoints, default to allowing all access (permission checked per-view)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# ===== JWT TOKEN CONFIGURATION =====
# 1-hour token lifetime with Bearer auth header
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Token valid for 1 hour of active use
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ===== CORS (CROSS-ORIGIN RESOURCE SHARING) =====
# Allow frontend (Next.js, Vite) to call backend from localhost:3000 and :5173
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

# ===== EMAIL CONFIGURATION (GMAIL SMTP) =====
# For verification codes and alert notifications
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'sharvikhadka@gmail.com')


# ===== STRIPE PAYMENT GATEWAY CONFIGURATION =====
# Subscription payments and billing
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')

# Frontend URL for success/failure redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# ===== SNORT IDS LOG INGESTION CONFIGURATION =====
# Directory for Snort logs, polling interval
SNORT_LOG_DIR = os.environ.get('SNORT_LOG_DIR', str(BASE_DIR.parent / 'real_logs'))
SNORT_POLL_INTERVAL_SECONDS = int(os.environ.get('SNORT_POLL_INTERVAL_SECONDS', '3'))

# ===== LOGGING CONFIGURATION =====
# Log all debug and error messages to console and file
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'subscription': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'alerts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'authentication': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}