# Generated by Django 4.2.16 on 2026-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(help_text='User-friendly display name (e.g., Basic plan, Professional plan)', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Enable email alerts for this plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(help_text='Maximum number of users for this plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Plan identifier (e.g., basic, professional, enterprise)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10),
        ),
    ]
