# Generated by Django 4.2.16 on 2026-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='name',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(help_text='Plan name (e.g., Basic plan, Professional plan)', max_length=100, unique=True),
        ),
    ]
