# Generated by Django 4.2.16 on 2026-03-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_organization_is_active_and_more'),
        ('subscription', '0003_remove_subscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='authentication.organization'),
        ),
    ]
