# Generated by Django 4.2.16 on 2026-04-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_organization_is_active'),
        ('subscription', '0005_alter_subscription_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in USD', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text='Currency code (e.g., usd, eur)', max_length=10)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True)),
                ('user_email', models.EmailField(help_text='User email for payment receipt', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization making payment', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
